#!/bin/bash

IP_LOCAL=$(ip addr show wlo1 | grep "inet " | awk '{print $2}' | cut -d/ -f1)
BASE_URL="http://tsilavina.mywebcommunity.org/urls.php"

DOMAIN=$(curl -s $BASE_URL \
| sed 's/\\\//\//g' \
| sed -n 's/.*"\(http[^"]*\)".*/\1/p' \
| sed 's#http[s]*://##')

# Ouvrir deux terminaux
mate-terminal &
mate-terminal &

sleep 2

# Récupérer les ID des fenêtres terminal
WIN1=$(xdotool search --onlyvisible --class mate-terminal | head -n 1)
WIN2=$(xdotool search --onlyvisible --class mate-terminal | tail -n 1)

# Terminal 1
xdotool windowactivate --sync $WIN1
xdotool type "pagekite.py $IP_LOCAL:9000 $DOMAIN"
xdotool key Return &

# Terminal 2
xdotool windowactivate --sync $WIN2
#xdotool type "systemctl restart multi-gorad"
#xdotool key Return &
sleep 3

xdotool type "firefox $IP_LOCAL:8000/multi-monitoring"
xdotool key Return &
